[Variables]

;======Button1======

Button1Path=["taskmgr.exe"]
Button1Text=TASK MANAGER

;======Button2======

Button2Path=["C:\Program Files\Paint.NET\PaintDotNet.exe"]
Button2Text="PAINT.NET"

;======Button3======

Button3Path=["C:\Program Files\Skype\Skype.exe"]
Button3Text="SKYPE"

;======Button4======

Button4Path=["C:\Program Files\Common Files\DVDVideoSoft\FreeStudioManager.exe"]
Button4Text="FREE STUDIO MANAGER"

;======Button5======

Button5Path=["C:\Program Files\Mozilla Firefox\firefox.exe"]
Button5Text="FIREFOX"

;======Button6======

Button6Path=["< INSERT APPLICATION PATH 6>"]
Button6Text="< INSERT APPLICATION NAME 6>"

;======Button7======

Button7Path=["< INSERT APPLICATION PATH 7>"]
Button7Text="< INSERT APPLICATION NAME 7>"

;======Button8======

Button8Path=["< INSERT APPLICATION PATH 8>"]
Button8Text="< INSERT APPLICATION NAME 8>"

;======Button9======

Button9Path=["< INSERT APPLICATION PATH 9>"]
Button9Text="< INSERT APPLICATION NAME 9>"

;======Button10======

Button10Path=["< INSERT APPLICATION PATH 10>"]
Button10Text="< INSERT APPLICATION NAME 10>"

;======Button11======

Button11Path=["< INSERT APPLICATION PATH 11>"]
Button11Text="< INSERT APPLICATION NAME 11>"
