[Variables]

CmdRank=COMMANDER
CmdName=Verglii

Player=WMP

PictureFolder=D:\

1Core=[!RainmeterToggleMeterGroup CPU1][!RainmeterToggleMeterGroup SFI]
2Core=[!RainmeterToggleMeterGroup CPU1][!RainmeterToggleMeterGroup CPU2][!RainmeterToggleMeterGroup SFI]
4Core=[!RainmeterToggleMeterGroup CPU1][!RainmeterToggleMeterGroup CPU2][!RainmeterToggleMeterGroup CPU4][!RainmeterToggleMeterGroup SFI]
8Core=[!RainmeterToggleMeterGroup CPU1][!RainmeterToggleMeterGroup CPU2][!RainmeterToggleMeterGroup CPU4][!RainmeterToggleMeterGroup CPU8]
12Core=[!RainmeterToggleMeterGroup CPU1][!RainmeterToggleMeterGroup CPU2][!RainmeterToggleMeterGroup CPU4][!RainmeterToggleMeterGroup CPU8][!RainmeterToggleMeterGroup CPU12]
CPUs=[!RainmeterToggleMeterGroup CPU1][!RainmeterToggleMeterGroup CPU2][!RainmeterToggleMeterGroup SFI]

Location=RSXX1334
Unit=m
Format=°C

URL1=http://news.google.com/news?pz=1&ned=us&hl=ru&topic=h&num=10&output=rss
URL1Name="Google News"

URL2=http://feeds.gawker.com/lifehacker/full
URL2Name=Lifehacker

DAHours=24



