[QLText]
	X=85r
	Y=27r
	H=55
	W=168
	FontFace=#F#
	FontSize=#F3#
	StringAlign=CenterCenter
	AntiAlias=1
	ClipString=1

[QL1]							;Quick links
	Meter=Button
	ButtonImage=#Path_2##Resolution#/Button1_#CS#.png
	X=#QColumn1#
	Y=#QLine1#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL1L#]


[QL1T]
	Meter=String
	MeterStyle=QLText
	Text=#QL1N#


[QL2]
	Meter=Button
	ButtonImage=#Path_2##Resolution#/Button1_#CS#.png
	X=#QColumn2#
	Y=#QLine1#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL2L#]

[QL2T]
	Meter=String
	MeterStyle=QLText
	Text=#QL2N#

[QL3]
	Meter=Button
	ButtonImage=#Path_2##Resolution#/Button1_#CS#.png
	X=#QColumn1#
	Y=#QLine2#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL3L#]

[QL3T]
	Meter=String
	MeterStyle=QLText
	Text=#QL3N#

[QL4]
	Meter=Button
	ButtonImage=#Path_2##Resolution#/Button1_#CS#.png
	X=#QColumn2#
	Y=#QLine2#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL4L#]

[QL4T]
	Meter=String
	MeterStyle=QLText
	Text=#QL4N#

[QL5]
	Meter=Button
	ButtonImage=#Path_2##Resolution#/Button1_#CS#.png
	X=#QColumn3#
	Y=#QLine1#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL5L#]

[QL5T]
	Meter=String
	MeterStyle=QLText
	Text=#QL5N#


[QL6]
	Meter=Button
	ButtonImage=#Path_2##Resolution#/Button1_#CS#.png
	X=#QColumn3#
	Y=#QLine2#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL6L#]

[QL6T]
	Meter=String
	MeterStyle=QLText
	Text=#QL6N#