[Variables]

QLU=110
QLD=150
QLL=950
QLR=1060

LMY1=155
LMY2=195
LMY3=235
LMY4=275
LMY5=315
LMY6=355
LMY7=395
LMY8=435
LMY9=475
LMY10=515
LMY11=555
LMY12=595

LMB1_1=йнлоэчреп
LMB1_2=жо/нгс
LMB1_3=мюйнохрекх
LMB1_4=охрюмхе
LMB1_5=STEAM
LMB1_6=онцндю
LMB1_7=мнбнярх
LMB1_8=мюярпнийх
LMB1_9=оюмекэ сопюбкемхъ
LMB1_10=опнхцпшбюрекэ
LMB1_11=намнбхрэ
LMB1_12=ябепмсрэ

;=================================================!Bangs============================================
;============================================
;Sounds========================================
SoundBeep1=[PLAY "#@#Sounds\Computer\Beep1.wav"]

;==============================================
;Commands1======================================
CoIn_On=[!SetVariable "CompInfo" "0"][!RainmeterWriteKeyValue Variables "CompInfo" "0" "#@#\Inc\Settings.inc"]
CoIn_Off=[!SetVariable "CompInfo" "1"][!RainmeterWriteKeyValue Variables "CompInfo" "1" "#@#\Inc\Settings.inc"]

CPU_MEM_On=[!SetVariable "CPU_MEM" "0"][!RainmeterWriteKeyValue Variables "CPU_MEM" "0" "#@#\Inc\Settings.inc"]
CPU_MEM_Off=[!SetVariable "CPU_MEM" "1"][!RainmeterWriteKeyValue Variables "CPU_MEM" "1" "#@#\Inc\Settings.inc"]


;===============================================
FONX=530
FONY=270
FONH=440
FONW=750

;Computer====================
;Head
CX1=540
CX2=810
CHeY=280
CH1=40
CH2=30
CW1=260
CW2=460

;Lines
CY1=345
CY2=385
CY3=425
CY4=475
CY5=515
CY6=555
CY7=605
CY8=645
CY9=685
;============================