[Variables]

Expand=EXPAND

;Settings
Done=DONE
Settings=SETTINGS

;Time|Date
Time=TIME
SubstDay="Sunday":"SUNDAY","Monday":"MONDAY","Tuesday":"TUESDAY","Wednesday":"WEDNESDAY","Thursday":"THURSDAY","Friday":"FRIDAY","Saturday":"SATURDAY"
SubstMonth="January":"JANUARY","February":"FEBRUARY","March":"MARCH","April":"APRIL","May":"MAY","June":"JUNE","July":"JULY","August":"AUGUST","September":"SEPTEMBER","October":"OCTOBER","November":"NOVEMBER","December":"DECEMBER"

;Left menu settings
AccessPanel1=ACCESS PANEL 1
AccessPanel2=ACCESS PANEL 2

;Left menu buttons
LMB1_1=COMPUTER
LMB1_2=CPU/RAM
LMB1_3=DISKS
LMB1_4=POWER
LMB1_5=STEAM
LMB1_6=WEATHER
LMB1_7=SCHEDULE
LMB1_8=SETTINGS
LMB1_9=CONTROL PANEL
LMB1_10=MEDIA PLAYER
LMB1_11=REFRESH
LMB1_12=HIDE

;Computer info
Name=NAME
Value=VALUE
CompName=COMPUTER NAME
UserName=USER NAME
Uptime=UPTIME
OS=OPERATIONAL SYSTEM
Processes=TOTAL PROCESSES
TProcess=TOP PROCESS
CPUName=CPU MODEL
PriGPU=PRIMARY GPU
RAMT=RAM TOTAL
SubstBit=
Byte=B
Days=DAYS
Hours=HOURS
Minutes=MINUTES

;CPU and memory
CP_Chrono=CPU CHRONOLOGY
PHY_Chrono=MEMORY CHRONOLOGY
CP_Ind=CPU LOAD INDICATORS
Indicators=INDICATORS
Graph=GRAPH
Core1N=CORE   1:
Core2N=CORE   2:
Core3N=CORE   3:
Core4N=CORE   4:
Core5N=CORE   5:
Core6N=CORE   6:
Core7N=CORE   7:
Core8N=CORE   8:
Core9N=CORE   9:
Core10N=CORE 10:
Core11N=CORE 11:
Core12N=CORE 12:
Memory=LOAD :

;Database
Search=SEARCH
Remember=REMEMBER PATH
RecycleBin=RECYCLE BIN
ClearBin=CLEAR
LeftMouseInfo=Left mouse button - Open file or folder
RightMouseInfo=Right mouse button - Open path in explorer

;Battery
BTSubs="0":"AC LINE","1":"CHARGING","2":"LOW","3":"NORMAL","4":"HIGHT"
BTSubs2="Unknown":"UNKNOWN"
PowerState_=POWER STATE
PowerTime=BACK-UP TIME
Shotdown=SHOTDOWN
Reload=RELOAD
Hibernation=HIBERNATION

;Steam
LibrarySteam=LIBRARY
NewsSteam=NEWS
SteamDownload=DOWNLOADS
SteamFriends=FRIENDS
SteamInventory=INVENTORY

;Schedule
Week1Text=1 week
Week2Text=2 week
ScheduleSettings=SETTINGS
HWeek1Text="‡••"
HWeek2Text="••‰"
WeekDay1=Monday
WeekDay2=Tuesday
WeekDay3=Wednesday
WeekDay4=Thursday
WeekDay5=Friday
WeekDay6=Saturday

;Settings
LMB1_0=GENERAL


;=Global
LCARSUserName=NAME
LCARSUserRank=RANK
LCARSColorScheme=COLOR SCHEME
LCARSFon=FON COLOR

QLAdress=Address

SettLink1=LINK 1
SettLink2=LINK 2
SettLink3=LINK 3
SettLink4=LINK 4
SettLink5=LINK 5
SettLink6=LINK 6
SettLink7=LINK 7
SettLink8=LINK 8
SettLink9=LINK 9
SettLink10=LINK 10
SettLink11=LINK 11
SettLink12=LINK 12

SettingsLinkName="Command name"
SettingsLinkCom="Command"

;ComputerInfo
LCARSCI_Head_Fon=Head color
LCARSCI_Normal_Fon=Data color

LCARSCM_A_Fon=Background of elements
LCARSCM_A_Core1=Core 1
LCARSCM_A_Core2=Core 2
LCARSCM_A_Core3=Core 3
LCARSCM_A_Core4=Core 4
LCARSCM_A_Core5=Core 5
LCARSCM_A_Core6=Core 6
LCARSCM_A_Core7=Core 7
LCARSCM_A_Core8=Core 8
LCARSCM_A_Core9=Core 9
LCARSCM_A_Core10=Core 10
LCARSCM_A_Core11=Core 11
LCARSCM_A_Core12=Core 12

LitCore=CORE
Lit234Cores=CORES
LitMoreCores=CORES