[Variables]

Expand=EXPAND

;Settings
Done=DONE
Settings=SETTINGS

;Time|Date
Time=TIME
SubstDay="Sunday":"SUNDAY","Monday":"MONDAY","Tuesday":"TUESDAY","Wednesday":"WEDNESDAY","Thursday":"THURSDAY","Friday":"FRIDAY","Saturday":"SATURDAY"
SubstMonth="January":"JANUARY","February":"FEBRUARY","March":"MARCH","April":"APRIL","May":"MAY","June":"JUNE","July":"JULY","August":"AUGUST","September":"SEPTEMBER","October":"OCTOBER","November":"NOVEMBER","December":"DECEMBER"

;Left menu settings
AccessPanel1=ACCESS PANEL 1
AccessPanel2=ACCESS PANEL 2

;Left menu buttons
LMB1_1=COMPUTER
LMB1_2=CPU/RAM
LMB1_3=DISKS
LMB1_4=POWER
LMB1_5=STEAM
LMB1_6=WEATHER
LMB1_7=NEWS
LMB1_8=SETTINGS
LMB1_9=CONTROL PANEL
LMB1_10=MEDIA PLAYER
LMB1_11=REFRESH
LMB1_12=HIDE

;Computer info
Name=NAME
Value=VALUE
CompName=COMPUTER NAME
UserName=USER NAME
Uptime=UPTIME
OS=OPERATIONAL SYSTEM
Processes=TOTAL PROCESSES
TProcess=TOP PROCESS
CPUName=CPU MODEL
PriGPU=PRIMARY GPU
RAMT=RAM TOTAL
SubstBit=
Byte=B
Days=DAYS
Hours=HOURS
Minutes=MINUTES

;CPU and memory
CP_Chrono=CPU CHRONOLOGY
PHY_Chrono=MEMORY CHRONOLOGY
CP_Ind=CPU LOAD INDICATORS
Indicators=INDICATORS
Graph=GRAPH
Core1N=CORE   1:
Core2N=CORE   2:
Core3N=CORE   3:
Core4N=CORE   4:
Core5N=CORE   5:
Core6N=CORE   6:
Core7N=CORE   7:
Core8N=CORE   8:
Core9N=CORE   9:
Core10N=CORE 10:
Core11N=CORE 11:
Core12N=CORE 12:
Memory=LOAD :

;Database
Search=SEARCH
Remember=REMEMBER PATH
RecycleBin=RECYCLE BIN
ClearBin=CLEAR
LeftMouseInfo=Left mouse button - Open file or folder
RightMouseInfo=Right mouse button - Open path in explorer

;Battery
BTSubs="0":"Œ“ —≈“»","1":"«¿–ﬂƒ ¿","2":"Õ»« Œ","3":"—–≈ƒÕ≈","4":"¬€—Œ Œ"
BTSubs2="Unknown":"UNKNOWN"
PowerState_=POWER STATE
PowerTime=POWER TIME
Shotdown=SHOTDOWN
Reload=RELOAD
Hibernation=HIBERNATION

;Steam
LibrarySteam=LIBRARY
NewsSteam=NEWS
SteamDownload=DOWNLOADS
SteamFriends=FRIENDS
SteamInventory=INVENTORY