[Variables]
;Settings
Done=цнрнбн

;Time|Date
SubstDay="Sunday":"бняйпеяемэе","Monday":"онмедекэмхй","Tuesday":"брнпмхй","Wednesday":"япедю","Thursday":"вербепц","Friday":"оърмхжю","Saturday":"ясаанрю"
SubstMonth="January":"ъмбюпъ","February":"тебпюкъ","March":"люпрю","April":"юопекъ","May":"люъ","June":"хчмъ","JulY":"хчкъ","August":"юбцсярю","September":"яемръапъ","October":"нйръапъ","November":"мнъапъ","December":"дейюапэ"

;Left menu settings
AccessPanel=оюмекэ днярсою

;Left menu buttons
LMB1_1=йнлоэчреп
LMB1_2=жо/нгс
LMB1_3=мюйнохрекх
LMB1_4=охрюмхе
LMB1_5=STEAM
LMB1_6=онцндю
LMB1_7=мнбнярх
LMB1_8=мюярпнийх
LMB1_9=оюмекэ сопюбкемхъ
LMB1_10=опнхцпшбюрекэ
LMB1_11=намнбхрэ
LMB1_12=ябепмсрэ

;Computer info
Name=ябниярбн
Value=гмювемхе
CompName=хлъ йнлоэчрепю
UserName=онкэгнбюрекэ
Uptime=бпелъ пюанрш
OS=ноепюжхнммюъ яхярелю
Processes=бяецн опнжеяянб
TProcess=нямнбмни опнжеяя
CPUName=лндекэ жемрпюкэмнцн опнжеяянпю
PriGPU=нямнбмюъ бхденйюпрю
RAMT=бяецн ноепюрхбмни оюлърх
SubstBit="G":"ц","M":"л","k":"Й"