[Variables]

Expand=пюгбепмсрэ

;Settings
Done=цнрнбн
Settings=мюярпнийю

;Time|Date
Time=бпелъ
SubstDay="Sunday":"бняйпеяемэе","Monday":"онмедекэмхй","Tuesday":"брнпмхй","Wednesday":"япедю","Thursday":"вербепц","Friday":"оърмхжю","Saturday":"ясаанрю"
SubstMonth="January":"ъмбюпъ","February":"тебпюкъ","March":"люпрю","April":"юопекъ","May":"люъ","June":"хчмъ","JulY":"хчкъ","August":"юбцсярю","September":"яемръапъ","October":"нйръапъ","November":"мнъапъ","December":"дейюапэ"

;Left menu settings
AccessPanel1=оюмекэ днярсою 1
AccessPanel2=оюмекэ днярсою 2

;Left menu buttons
LMB1_1=йнлоэчреп
LMB1_2=жо/нгс
LMB1_3=мюйнохрекх
LMB1_4=охрюмхе
LMB1_5=STEAM х хцпш
LMB1_6=онцндю
LMB1_7=пюяохяюмхе
LMB1_8=мюярпнийх
LMB1_9=оюмекэ сопюбкемхъ
LMB1_10=опнхцпшбюрекэ
LMB1_11=намнбхрэ
LMB1_12=ябепмсрэ


;Computer info
Name=ябниярбн
Value=гмювемхе
CompName=хлъ йнлоэчрепю
UserName=онкэгнбюрекэ
Uptime=бпелъ пюанрш
OS=ноепюжхнммюъ яхярелю
Processes=бяецн опнжеяянб
TProcess=нямнбмни опнжеяя
CPUName=лндекэ жемрпюкэмнцн опнжеяянпю
PriGPU=нямнбмюъ бхденйюпрю
RAMT=бяецн ноепюрхбмни оюлърх
SubstBit="G":"ц","M":"л","k":"Й"
Byte=а
Days=дмеи
Hours=вюянб
Minutes=лхмср

;CPU and memory
CP_Chrono=упнмнкнцхъ гюцпсгйх жо
PHY_Chrono=упнмнкнцхъ нгс
CP_Ind=хмдхйюрнпш гюцпсгйх жо
Indicators=хмдхйюрнпш
Graph=цпютхй
Core1N=ъдпн   1:
Core2N=ъдпн   2:
Core3N=ъдпн   3:
Core4N=ъдпн   4:
Core5N=ъдпн   5:
Core6N=ъдпн   6:
Core7N=ъдпн   7:
Core8N=ъдпн   8:
Core9N=ъдпн   9:
Core10N=ъдпн 10:
Core11N=ъдпн 11:
Core12N=ъдпн 12:
Memory=гюмърн :

;Database
Search=онхяй
Remember=гюонлмхрэ
RecycleBin=йнпгхмю
ClearBin=нвхярхрэ
LeftMouseInfo=кЕБЮЪ ЙМНОЙЮ ЛШЬХ - НРЙПШРЭ ТЮИК ХКХ ОЮОЙС
RightMouseInfo=оПЮБЮЪ ЙМНОЙЮ ЛШЬХ - НРЙПШРЭ Б ОПНБНДМХЙЕ РЕЙСЫСЧ ОЮОЙС

;Battery
BTSubs="0":"нр яерх","1":"гюпъдйю","2":"мхгйн","3":"япедме","4":"бшянйн"
BTSubs2="Unknown":"мехгбеярмн"
PowerState_=янярнъмхе охрюмхъ
PowerTime=бпелъ гюпъдю
Shotdown=бшйкчвемхе
Reload=оепегюцпсгйю
Hibernation=цхаепмюжхъ

;Steam
LibrarySteam=ахакхнрейю
NewsSteam=мнбнярх
SteamDownload=гюцпсгйх
SteamFriends=дпсгэъ
SteamInventory=хмбемрюпэ

;Schedule
Week1Text=1 МЕДЕКЪ
Week2Text=2 МЕДЕКЪ
ScheduleSettings=мюярпнийю
HWeek1Text="┤∙∙"
HWeek2Text="∙∙┴"
WeekDay1=оНМЕДЕКЭМХЙ
WeekDay2=бРНПМХЙ
WeekDay3=яПЕДЮ
WeekDay4=вЕРБЕПЦ
WeekDay5=оЪРМХЖЮ
WeekDay6=яСААНРЮ