[Variables]

Expand=РАЗВЕРНУТЬ

;Settings
Done=ГОТОВО
Settings=НАСТРОЙКА

;Time|Date
Time=ВРЕМЯ
SubstDay="Sunday":"ВОСКРЕСЕНЬЕ","Monday":"ПОНЕДЕЛЬНИК","Tuesday":"ВТОРНИК","Wednesday":"СРЕДА","Thursday":"ЧЕТВЕРГ","Friday":"ПЯТНИЦА","Saturday":"СУББОТА"
SubstMonth="January":"ЯНВАРЯ","February":"ФЕВРАЛЯ","March":"МАРТА","April":"АПРЕЛЯ","May":"МАЯ","June":"ИЮНЯ","JulY":"ИЮЛЯ","August":"АВГУСТА","September":"СЕНТЯБРЯ","October":"ОКТЯБРЯ","November":"НОЯБРЯ","December":"ДЕКАБРЬ"

;Left menu settings
AccessPanel1=МЕНЮ 1
AccessPanel2=МЕНЮ 2

;Left menu buttons
LMB1_1=КОМПЬЮТЕР
LMB1_2=ЦП/ОЗУ
LMB1_3=НАКОПИТЕЛИ
LMB1_4=ПИТАНИЕ
LMB1_5=STEAM И ИГРЫ
LMB1_6=ПОГОДА
LMB1_7=РАСПИСАНИЕ
LMB1_8=СОЛНЦЕ
LMB1_9=НАСТРОЙКИ
LMB1_10=ПАНЕЛЬ УПРАВЛЕНИЯ
LMB1_11=ОБНОВИТЬ
LMB1_12=СВЕРНУТЬ
LMB1_OFF=X
LMB_Center=ФУНКЦИИ

LMBF_1=КОМПЬЮТЕР
LMBF_2=ЦП/ОЗУ
LMBF_3=НАКОПИТЕЛИ
LMBF_4=ПИТАНИЕ
LMBF_5=STEAM И ИГРЫ
LMBF_6=ПОГОДА
LMBF_7=РАСПИСАНИЕ
LMBF_8=СОЛНЦЕ
LMBF_9=НАСТРОЙКИ
LMBF_10=ПАНЕЛЬ УПРАВЛЕНИЯ
LMBF_11=ОБНОВИТЬ
LMBF_12=СВЕРНУТЬ
LMBF_OFF=


;Computer info
Name=СВОЙСТВО
Value=ЗНАЧЕНИЕ
CompName=ИМЯ КОМПЬЮТЕРА
UserName=ПОЛЬЗОВАТЕЛЬ
Uptime=ВРЕМЯ РАБОТЫ
OS=ОПЕРАЦИОННАЯ СИСТЕМА
Processes=ВСЕГО ПРОЦЕССОВ
TProcess=ОСНОВНОЙ ПРОЦЕСС
CPUName=МОДЕЛЬ ЦЕНТРАЛЬНОГО ПРОЦЕССОРА
PriGPU=ОСНОВНАЯ ВИДЕОКАРТА
RAMT=ВСЕГО ОПЕРАТИВНОЙ ПАМЯТИ
SubstBit="G":"Г","M":"М","k":"к"
Byte=Б
Days=ДНЕЙ
Hours=ЧАСОВ
Minutes=МИНУТ

;CPU and memory
CP_Chrono=ХРОНОЛОГИЯ ЗАГРУЗКИ ЦП
PHY_Chrono=ХРОНОЛОГИЯ ОЗУ
CP_Ind=ИНДИКАТОРЫ ЗАГРУЗКИ ЦП
Indicators=ИНДИКАТОРЫ
Graph=ГРАФИК
Core1N=ЯДРО   1:
Core2N=ЯДРО   2:
Core3N=ЯДРО   3:
Core4N=ЯДРО   4:
Core5N=ЯДРО   5:
Core6N=ЯДРО   6:
Core7N=ЯДРО   7:
Core8N=ЯДРО   8:
Core9N=ЯДРО   9:
Core10N=ЯДРО 10:
Core11N=ЯДРО 11:
Core12N=ЯДРО 12:
Memory=ЗАНЯТО :

;Database
Search=ПОИСК
Remember=ЗАПОМНИТЬ
RecycleBin=КОРЗИНА
ClearBin=ОЧИСТИТЬ
LeftMouseInfo=Левая кнопка мыши - открыть файл или папку
RightMouseInfo=Правая кнопка мыши - открыть в проводнике текущую папку

;Battery
BTSubs="0":"ОТ СЕТИ","1":"ЗАРЯДКА","2":"НИЗКО","3":"СРЕДНЕ","4":"ВЫСОКО"
BTSubs2="Unknown":"НЕИЗВЕСТНО"
PowerState_=СОСТОЯНИЕ ПИТАНИЯ
PowerTime=ВРЕМЯ ЗАРЯДА
Shotdown=ВЫКЛЮЧЕНИЕ
Reload=ПЕРЕЗАГРУЗКА
Hibernation=ГИБЕРНАЦИЯ

;Steam
LibrarySteam=БИБЛИОТЕКА
NewsSteam=НОВОСТИ
SteamDownload=ЗАГРУЗКИ
SteamFriends=ДРУЗЬЯ
SteamInventory=ИНВЕНТАРЬ

;Schedule
Week1Text=1 неделя
Week2Text=2 неделя
ScheduleSettings=НАСТРОЙКА
HWeek1Text="‡••"
HWeek2Text="••‰"
WeekDay1=Понедельник
WeekDay2=Вторник
WeekDay3=Среда
WeekDay4=Четверг
WeekDay5=Пятница
WeekDay6=Суббота

;Settings
LMB1_0=ОБЩИЕ


;=Global
LCARSUserName=ИМЯ
LCARSUserRank=РАНГ
LCARSColorScheme=ЦВЕТОВАЯ СХЕМА
LCARSFon=ЦВЕТ ФОНА

QLAdress=Адрес

SettLink1=Ссылка 1
SettLink2=Ссылка 2
SettLink3=Ссылка 3
SettLink4=Ссылка 4
SettLink5=Ссылка 5
SettLink6=Ссылка 6
SettLink7=Ссылка 7
SettLink8=Ссылка 8
SettLink9=Ссылка 9
SettLink10=Ссылка 10
SettLink11=Ссылка 11
SettLink12=Ссылка 12

SettingsLinkName="Имя комманды"
SettingsLinkCom="Комманда"

;ComputerInfo
LCARSCI_Head_Fon=Цвет шапки
LCARSCI_Normal_Fon=Цвет данных

LCARSCM_A_Fon=Фон элементов
LCARSCM_A_Core1=Ядро 1
LCARSCM_A_Core2=Ядро 2
LCARSCM_A_Core3=Ядро 3
LCARSCM_A_Core4=Ядро 4
LCARSCM_A_Core5=Ядро 5
LCARSCM_A_Core6=Ядро 6
LCARSCM_A_Core7=Ядро 7
LCARSCM_A_Core8=Ядро 8
LCARSCM_A_Core9=Ядро 9
LCARSCM_A_Core10=Ядро 10
LCARSCM_A_Core11=Ядро 11
LCARSCM_A_Core12=Ядро 12
LCARSCM_A_PhyMem=Оперативная память

LitCore=ЯДРО
Lit234Cores=ЯДРА
LitMoreCores=ЯДЕР

;Database
LCARSDB_Head_Fon=Цвет адреса
LCARSDB_Normal_Fon=Цвет данных

SettingsAdressName="Название"
SettingsAdressVal="Путь"

;LMBControl
TLMButton1=Кнопка 1
TLMButton2=Кнопка 2
TLMButton3=Кнопка 3
TLMButton4=Кнопка 4
TLMButton5=Кнопка 5
TLMButton6=Кнопка 6
TLMButton7=Кнопка 7
TLMButton8=Кнопка 8
TLMButton9=Кнопка 9
TLMButton10=Кнопка 10
TLMButton11=Кнопка 11
TLMButton12=Кнопка 12