[Variables]
Week1Day1_1=-
Week1Day1_2=-
Week1Day1_3=Информатика, 1 группа
Week1Day1_4=Информатика, 2 группа
Week1Day1_5=17:10 Основы телевидения
Week1Day1_6=-

Week1Day2_1=Допуски и посадки
Week1Day2_2=Иностранный язык
Week1Day2_3=Экология
Week1Day2_4=БЖД
Week1Day2_5=-
Week1Day2_6=-

Week1Day3_1=-
Week1Day3_2=-
Week1Day3_3=-
Week1Day3_4=-
Week1Day3_5=-
Week1Day3_6=-

Week1Day4_1=-
Week1Day4_2=-
Week1Day4_3=-
Week1Day4_4=-
Week1Day4_5=-
Week1Day4_6=-

Week1Day5_1=-
Week1Day5_2=-
Week1Day5_3=-
Week1Day5_4=-
Week1Day5_5=-
Week1Day5_6=-

Week1Day6_1=-
Week1Day6_2=-
Week1Day6_3=-
Week1Day6_4=-
Week1Day6_5=-
Week1Day6_6=-

Week2Day1_1=-
Week2Day1_2=-
Week2Day1_3=-
Week2Day1_4=-
Week2Day1_5=-
Week2Day1_6=-

Week2Day2_1=1 пара
Week2Day2_2=2 пара
Week2Day2_3=3 пара
Week2Day2_4=4 пара
Week2Day2_5=5 пара
Week2Day2_6=6 пара

Week2Day3_1=1 пара
Week2Day3_2=2 пара
Week2Day3_3=3 пара
Week2Day3_4=4 пара
Week2Day3_5=5 пара
Week2Day3_6=6 пара

Week2Day4_1=1 пара
Week2Day4_2=2 пара
Week2Day4_3=3 пара
Week2Day4_4=4 пара
Week2Day4_5=5 пара
Week2Day4_6=6 пара

Week2Day5_1=1 пара
Week2Day5_2=2 пара
Week2Day5_3=3 пара
Week2Day5_4=4 пара
Week2Day5_5=5 пара
Week2Day5_6=6 пара

Week2Day6_1=1 пара
Week2Day6_2=2 пара
Week2Day6_3=3 пара
Week2Day6_4=4 пара
Week2Day6_5=5 пара
Week2Day6_6=6 пара