[Variables]
CS=PRI

MediaPlayer=WMP

LMC1=0
LMC2=1

FONHID=0

FONX=530
FONY=270
FONH=440
FONW=640

CompInfo=1
CPU_MEM=1
CPU_MEM0=1
CPU_MEM1=1
DATABASE=0
PowerSource=1
STEAM_=1
Weather_=1
News_=0
MediaPl=0

DATABASELinksBorder=1
;Drive1
D1=C
;Drive2
D2=D

;Links
LMCT1=ÃŒ…  ŒÃœ‹ﬁ“≈–
LMCL1="::{20D04FE0-3AEA-1069-A2D8-08002B30309D}"

LMCT2=——€À ¿ 2
LMCL2=

LMCT3=——€À ¿ 3
LMCL3=

LMCT4=——€À ¿ 4
LMCL4=

LMCT5=——€À ¿ 5
LMCL5=

LMCT6=——€À ¿ 6
LMCL6=

LMCT7=——€À ¿ 7
LMCL7=

LMCT8=——€À ¿ 8
LMCL8=

LMCT9=——€À ¿ 9
LMCL9=

LMCT10=——€À ¿ 10
LMCL10=

LMCT11=——€À ¿ 11
LMCL11=

LMCT12=——€À ¿ 12
LMCL12=

;Quick links
QL1N=deviantART
QL1L=http://deviantart.com/

QL2N=Google
QL2L=http://google.com/

QL3N=¬ÍÓÌÚ‡ÍÚÂ
QL3L=http://vk.com/

QL4N=YouTube
QL4L=http://youtube.com

QL5N=LCARS
QL5L=http://www.bracercom.com/tutorial/content/CoherentLCARSInterface/LCARSCoherentInterface.html

QL6N=Yandex
QL6L=http://Yandex.ru

GR|IND=0
IND|GR=1

CPULCount=4

CP1=1
CP2=1
CP3=1
CP4=1
CP5=1
CP6=1
CP7=1
CP8=1
CP9=1
CP10=1
CP11=1
CP12=1

CP1_=0
CP2_=0
CP3_=0
CP4_=0
CP5_=1
CP6_=1
CP7_=1
CP8_=1
CP9_=1
CP10_=1
CP11_=1
CP12_=1

;Database=================
FBLB1Name= ÓÏÔ¸˛ÚÂ
FBLCom1=[!SetOption MeasurePath Path ""][!CommandMeasure MeasurePath Update]
FBLB1Path=
FBLB2Path=C:\
FBLB2Name=C
FBLCom2=[!SetOption MeasurePath Path "C:\"][!CommandMeasure MeasurePath Update]
FBLB3Path=D:\
FBLB3Name=D
FBLCom3=[!SetOption MeasurePath Path "D:\"][!CommandMeasure MeasurePath Update]
FBLB4Path=D:\Programs\
FBLB4Name=Programs
FBLCom4=[!SetOption MeasurePath Path "C:\Programs"][!CommandMeasure MeasurePath Update]

SHMP=0
FORMATMP=0

LastPlace=D:\
