[Variables]
CS=PRI

MediaPlayer=WMP

LMC1=0
LMC2=1

FONHID=0

CompInfo=0
CPU_MEM=1

;Drive1
D1=C
;Drive2
D2=D

;Links
LMCT1=ÃŒ…  ŒÃœ‹ﬁ“≈–
LMCL1="::{20D04FE0-3AEA-1069-A2D8-08002B30309D}"

LMCT2=——€À ¿ 2
LMCL2=

LMCT3=——€À ¿ 3
LMCL3=

LMCT4=——€À ¿ 4
LMCL4=

LMCT5=——€À ¿ 5
LMCL5=

LMCT6=——€À ¿ 6
LMCL6=

LMCT7=——€À ¿ 7
LMCL7=

LMCT8=——€À ¿ 8
LMCL8=

LMCT9=——€À ¿ 9
LMCL9=

LMCT10=——€À ¿ 10
LMCL10=

LMCT11=——€À ¿ 11
LMCL11=

LMCT12=——€À ¿ 12
LMCL12=

;Quick links
QL1N=deviantART
QL1L=http://deviantart.com/

QL2N=Google
QL2L=http://google.com/

QL3N=¬ÍÓÌÚ‡ÍÚÂ
QL3L=http://vk.com/

QL4N=YouTube
QL4L=http://youtube.com

CP0=1
CP1=1
CP2=1
CP3=1
CP4=1
CP5=1
CP6=1
CP7=1
CP8=1
CP9=1
CP10=1
CP11=1
CP12=1

CP0_=1
CP1_=1
CP2_=1
CP3_=1
CP4_=1
CP5_=1
CP6_=1
CP7_=1
CP8_=1
CP9_=1
CP10_=1
CP11_=1
CP12_=1
