[Variables]
CS=1

Lang=RUS

LMC1=0
LMC2=1

FONHID=0

FONX=530
FONY=270
FONH=440
FONW=640

CompInfo=1
CPU_MEM=1
CPU_MEM0=1
CPU_MEM1=1
DATABASE=1
PowerSource=1
STEAM_=0
Weather_=1
Schedule_=1
Sun=1

LMB1=1
LMB2=2
LMB3=3
LMB4=4
LMB5=5
LMB6=6
LMB7=7
LMB8=8
LMB9=9
LMB10=10
LMB11=11
LMB12=12

LMBSetV=1

DATABASELinksBorder=1
;Drive1
D1=C
;Drive2
D2=D

LinkNum=

LMCT=
LMCL=

;Links
LMCT1=МОЙ КОМПЬЮТЕР
LMCL1=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

LMCT2=ССЫЛКА 2
LMCL2=

LMCT3=ССЫЛКА 3
LMCL3=

LMCT4=ССЫЛКА 4
LMCL4=

LMCT5=ССЫЛКА 5
LMCL5=

LMCT6=ССЫЛКА 6
LMCL6=

LMCT7=ССЫЛКА 7
LMCL7=

LMCT8=ССЫЛКА 8
LMCL8=

LMCT9=ССЫЛКА 9
LMCL9=

LMCT10=ССЫЛКА 10
LMCL10=

LMCT11=ССЫЛКА 11
LMCL11=

LMCT12=ССЫЛКА 12
LMCL12=

;Quick links
QL
QLN
QLL


QL1N=deviantART
QL1L=http://deviantart.com/

QL2N=Google
QL2L=http://google.com/

QL3N=Вконтакте
QL3L=http://vk.com/

QL4N=YouTube
QL4L=http://youtube.com

QL5N=LCARS
QL5L=http://www.bracercom.com/tutorial/content/CoherentLCARSInterface/LCARSCoherentInterface.html

QL6N=Yandex
QL6L=http://Yandex.ru

GR|IND=1
IND|GR=0

CPULCount=4

CP1=0
CP2=0
CP3=0
CP4=0
CP5=1
CP6=1
CP7=1
CP8=1
CP9=1
CP10=1
CP11=1
CP12=1

CPN2=0
CPN3=0
CPN4=0
CPN5=0
CPN6=0
CPN7=0
CPN8=0
CPN9=0
CPN10=0
CPN11=0
CPN12=0

;Database=================
AdrNum=
AdrName=
AdrVal=

FBLB1Path=
FBLB2Path=C:\
FBLB3Path=D:\
FBLB4Path=D:\Programs\
FBLB1Name=Компьютер
FBLB2Name=C
FBLB3Name=D
FBLB4Name=Programs
FBLCom1=[!SetOption MeasurePath Path "#FBLB1Path#"][!CommandMeasure MeasurePath Update]
FBLCom2=[!SetOption MeasurePath Path "#FBLB2Path#"][!CommandMeasure MeasurePath Update]
FBLCom3=[!SetOption MeasurePath Path "#FBLB3Path#"][!CommandMeasure MeasurePath Update]
FBLCom4=[!SetOption MeasurePath Path "#FBLB4Path#"][!CommandMeasure MeasurePath Update]

SHMP=0
FORMATMP=0

LastPlace=

;Weather==================
URL=http://www.foreca.ru/Russia/Trekhgornyy
UpdateRateWeather=5000

Country1=Russia
City1=Trekhgornyy
City1Name=Трёхгорный
Country2=Russia
City2=Moskow
City2Name=Москва
Country3=Russia
City3=Chelyabinsk
City3Name=Челябинск

WeatherSettings=НАСТРОЙКА
;Schedule=================
WeekNumber=1
WeekHNumber=1

;Settings=================
Settings_Stage=1
SSt0=1
SSt1=0
SSt2=1
SSt3=1
SSt4=1
SSt5=1
SSt6=1
SSt7=1
SSt8=1

;Global
LCARSUserNameVar=Verglii
LCARSUserRankVar=Коммандер
SSt9=1
