[Elbos1]
	Meter=IMAGE
	ImageName=#@#/Static/Elbos/Elbos1_#CS#.png
	X=0
	Y=0
	AntiAlias=1

[Elbos1Block1]
	Meter=Image
	X=230
	Y=0
	W=836
	H=50
	SolidColor=#ELBOS#

[Elbos1End]
	Meter=IMAGE
	ImageName=#@#/Static/Elbos/Elbos1End_#CS#.png
	X=1331
	Y=0
	AntiAlias=1

[Elbos1OverlayText]
	Meter=STRING
	Text="LCARS-8923741"
	X=10r
	Y=-5
	FontFace=#F#
	FontSize=#F6#
	FontColor=#COL2#
	StringAlign=Right
	AntiAlias=1

[Elbos5]
	Meter=Image
	ImageName=#@#/Static/Elbos/Elbos3_#CS#.png
	X=506
	Y=160
	AntiAlias=1
	ImageFlip=Vertical

[Elbos5Block1]
	Meter=Image
	X=506
	Y=130
	W=100
	H=30
	SolidColor=#ELBOS#

[Elbos5Block2]
	Meter=Image
	X=646
	Y=190
	W=580
	H=30
	SolidColor=#ELBOS#

[Elbos5Block3]
	Meter=Image
	X=1236
	Y=190
	W=130
	H=30
	SolidColor=#ELBOS#