function SpawnText()
NS='#CRLF#'
W=tostring(SKIN:GetVariable('WeekNumber'))
HW=tonumber(SKIN:GetVariable('WeekHNumber'))
D1Name=tostring(SKIN:GetVariable('WeekDay1'))
D2Name=tostring(SKIN:GetVariable('WeekDay2'))
D3Name=tostring(SKIN:GetVariable('WeekDay3'))
D4Name=tostring(SKIN:GetVariable('WeekDay4'))
D5Name=tostring(SKIN:GetVariable('WeekDay5'))
D6Name=tostring(SKIN:GetVariable('WeekDay6'))

	if HW == 1 then
		SKIN:Bang('!SetOption', 'IndexDay1Name', 'Text', D1Name)
		SKIN:Bang('!SetOption', 'IndexDay2Name', 'Text', D2Name)
		SKIN:Bang('!SetOption', 'IndexDay3Name', 'Text', D3Name)
		local D1_1=tostring(SKIN:GetVariable('Week1Day1_1'))
		local D1_2=tostring(SKIN:GetVariable('Week1Day1_2'))
		local D1_3=tostring(SKIN:GetVariable('Week1Day1_3'))
		local D1_4=tostring(SKIN:GetVariable('Week1Day1_4'))
		local D1_5=tostring(SKIN:GetVariable('Week1Day1_5'))
		local D1_6=tostring(SKIN:GetVariable('Week1Day1_6'))
		SKIN:Bang('!SetOption', 'IndexDay1Text', 'Text', D1_1..NS..D1_2..NS..D1_3..NS..D1_4..NS..D1_5..NS..D1_6)
		local D2_1=tostring(SKIN:GetVariable('Week1Day2_1'))
		local D2_2=tostring(SKIN:GetVariable('Week1Day2_2'))
		local D2_3=tostring(SKIN:GetVariable('Week1Day2_3'))
		local D2_4=tostring(SKIN:GetVariable('Week1Day2_4'))
		local D2_5=tostring(SKIN:GetVariable('Week1Day2_5'))
		local D2_6=tostring(SKIN:GetVariable('Week1Day2_6'))
		SKIN:Bang('!SetOption', 'IndexDay2Text', 'Text', D2_1..NS..D2_2..NS..D2_3..NS..D2_4..NS..D2_5..NS..D2_6)
		local D3_1=tostring(SKIN:GetVariable('Week1Day3_1'))
		local D3_2=tostring(SKIN:GetVariable('Week1Day3_2'))
		local D3_3=tostring(SKIN:GetVariable('Week1Day3_3'))
		local D3_4=tostring(SKIN:GetVariable('Week1Day3_4'))
		local D3_5=tostring(SKIN:GetVariable('Week1Day3_5'))
		local D3_6=tostring(SKIN:GetVariable('Week1Day3_6'))
		SKIN:Bang('!SetOption', 'IndexDay3Text', 'Text', D3_1..NS..D3_2..NS..D3_3..NS..D3_4..NS..D3_5..NS..D3_6)
	else
		SKIN:Bang('!SetOption', 'IndexDay1Name', 'Text', D4Name)
		SKIN:Bang('!SetOption', 'IndexDay2Name', 'Text', D5Name)
		SKIN:Bang('!SetOption', 'IndexDay3Name', 'Text', D6Name)
		local D1_1=tostring(SKIN:GetVariable('Week1Day4_1'))
		local D1_2=tostring(SKIN:GetVariable('Week1Day4_2'))
		local D1_3=tostring(SKIN:GetVariable('Week1Day4_3'))
		local D1_4=tostring(SKIN:GetVariable('Week1Day4_4'))
		local D1_5=tostring(SKIN:GetVariable('Week1Day4_5'))
		local D1_6=tostring(SKIN:GetVariable('Week1Day4_6'))
		SKIN:Bang('!SetOption', 'IndexDay1Text', 'Text', D1_1..NS..D1_2..NS..D1_3..NS..D1_4..NS..D1_5..NS..D1_6)
		local D2_1=tostring(SKIN:GetVariable('Week1Day5_1'))
		local D2_2=tostring(SKIN:GetVariable('Week1Day5_2'))
		local D2_3=tostring(SKIN:GetVariable('Week1Day5_3'))
		local D2_4=tostring(SKIN:GetVariable('Week1Day5_4'))
		local D2_5=tostring(SKIN:GetVariable('Week1Day5_5'))
		local D2_6=tostring(SKIN:GetVariable('Week1Day5_6'))
		SKIN:Bang('!SetOption', 'IndexDay2Text', 'Text', D2_1..NS..D2_2..NS..D2_3..NS..D2_4..NS..D2_5..NS..D2_6)
		local D3_1=tostring(SKIN:GetVariable('Week1Day6_1'))
		local D3_2=tostring(SKIN:GetVariable('Week1Day6_2'))
		local D3_3=tostring(SKIN:GetVariable('Week1Day6_3'))
		local D3_4=tostring(SKIN:GetVariable('Week1Day6_4'))
		local D3_5=tostring(SKIN:GetVariable('Week1Day6_5'))
		local D3_6=tostring(SKIN:GetVariable('Week1Day6_6'))
		SKIN:Bang('!SetOption', 'IndexDay3Text', 'Text', D3_1..NS..D3_2..NS..D3_3..NS..D3_4..NS..D3_5..NS..D3_6)
	end
end