[QL1]							;Quick links
	Meter=Button
	ButtonImage=#@#/Buttons/Button1#CS#.png
	X=#QLL#
	Y=#QLU#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL1L#]


[QL1T]
	Meter=String
	X=-10R
	Y=15r
	H=30
	W=80
	Text=#QL1N#
	FontFace=#F#
	FontSize=#F3#
	StringAlign=RightCenter
	AntiAlias=1
	ClipString=1

[QL2]
	Meter=Button
	ButtonImage=#@#/Buttons/Button1#CS#.png
	X=#QLR#
	Y=#QLU#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL2L#]

[QL2T]
	Meter=String
	X=-10R
	Y=15r
	H=30
	W=80
	Text=#QL2N#
	FontFace=#F#
	FontSize=#F3#
	StringAlign=RightCenter
	AntiAlias=1
	ClipString=1

[QL3]
	Meter=Button
	ButtonImage=#@#/Buttons/Button1#CS#.png
	X=#QLL#
	Y=#QLD#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL3L#]

[QL3T]
	Meter=String
	X=-10R
	Y=15r
	H=30
	W=80
	Text=#QL3N#
	FontFace=#F#
	FontSize=#F3#
	StringAlign=RightCenter
	AntiAlias=1
	ClipString=1

[QL4]
	Meter=Button
	ButtonImage=#@#/Buttons/Button1#CS#.png
	X=#QLR#
	Y=#QLD#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL4L#]

[QL4T]
	Meter=String
	X=-10R
	Y=15r
	H=30
	W=80
	Text=#QL4N#
	FontFace=#F#
	FontSize=#F3#
	StringAlign=RightCenter
	AntiAlias=1
	ClipString=1

[QL5]
	Meter=Button
	ButtonImage=#@#/Buttons/Button1#CS#.png
	X=#QLRR#
	Y=#QLU#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL5L#]

[QL5T]
	Meter=String
	X=-10R
	Y=15r
	H=30
	W=80
	Text=#QL5N#
	FontFace=#F#
	FontSize=#F3#
	StringAlign=RightCenter
	AntiAlias=1
	ClipString=1

[QL6]
	Meter=Button
	ButtonImage=#@#/Buttons/Button1#CS#.png
	X=#QLRR#
	Y=#QLD#
	AntiAlias=1
	ButtonCommand=!Execute #SoundBeep1#[#QL6L#]

[QL6T]
	Meter=String
	X=-10R
	Y=15r
	H=30
	W=80
	Text=#QL6N#
	FontFace=#F#
	FontSize=#F3#
	StringAlign=RightCenter
	AntiAlias=1
	ClipString=1