[Variables]
QLU=110
QLD=150
QLL=950
QLR=1060
QLRR=1170

LMY1=145
LMYO=10R


Fon1=[!SetVariable "FONH" "440"][!RainmeterWriteKeyValue Variables "FONH" "440" "#@#\Inc\Settings.inc"][!SetVariable "FONW" "750"][!RainmeterWriteKeyValue Variables "FONW" "750" "#@#\Inc\Settings.inc"][!SetVariable "FONX" "530"][!RainmeterWriteKeyValue Variables "FONX" "530" "#@#\Inc\Settings.inc"][!SetVariable "FONY" "270"][!RainmeterWriteKeyValue Variables "FONY" "270" "#@#\Inc\Settings.inc"]
Fon2=[!SetVariable "FONH" "440"][!RainmeterWriteKeyValue Variables "FONH" "440" "#@#\Inc\Settings.inc"][!SetVariable "FONW" "640"][!RainmeterWriteKeyValue Variables "FONW" "640" "#@#\Inc\Settings.inc"][!SetVariable "FONX" "530"][!RainmeterWriteKeyValue Variables "FONX" "530" "#@#\Inc\Settings.inc"][!SetVariable "FONY" "270"][!RainmeterWriteKeyValue Variables "FONY" "270" "#@#\Inc\Settings.inc"]
Fon3=[!SetVariable "FONH" "185"][!RainmeterWriteKeyValue Variables "FONH" "185" "#@#\Inc\Settings.inc"][!SetVariable "FONW" "490"][!RainmeterWriteKeyValue Variables "FONW" "490" "#@#\Inc\Settings.inc"][!SetVariable "FONX" "680"][!RainmeterWriteKeyValue Variables "FONX" "680" "#@#\Inc\Settings.inc"][!SetVariable "FONY" "270"][!RainmeterWriteKeyValue Variables "FONY" "270" "#@#\Inc\Settings.inc"]
;===============================================

;Computer====================
;Head
CX1=540
CX2=810
CHeY=280
CH1=40
CH2=30
CW1=260
CW2=460

;Lines
CY1=345
CY2=385
CY3=425
CY4=475
CY5=515
CY6=555
CY7=605
CY8=645
CY9=685
;============================

;Database=================
IcSize=40
NameH=40
NameW=550
IcW=600

IcX1=550
IcX2=600

IcY1=340
IcY2=(#IcY1#+#IcSize#+#IcYD#)
IcY3=(#IcY2#+#IcSize#+#IcYD#)
IcY4=(#IcY3#+#IcSize#+#IcYD#)
IcY5=(#IcY4#+#IcSize#+#IcYD#)
IcY6=(#IcY5#+#IcSize#+#IcYD#)
IcYD=10
;=========================

;=================================Steam
GameIconX=550
GameIcon1Y=290
GameIcon2Y=410
GameIcon3Y=530
GameIconH=70
GameIconW=100
GameNameH=40

SteamIconX=900
SteamIconY=370