[FonWeather1]
	Meter=Image
	X=540
	Y=280
	W=200
	H=210
	SolidColor=#FONWeath#
	Hidden=#Weather_#
	DynamicVariables=1

;//////////////////////////////////////
[WMeterFO]
Meter=String
MeasureName=WMeasureFO
X=1005
Y=280
W=310
H=100
FontColor=#COL2#
FontFace=#F#
StringAlign=Center
FontSize=#F5#
AntiAlias=1
ClipString=1
SolidColor=#FONWeath#

[WMeterName]
Meter=String
MeasureName=WMeasureName
X=1005
Y=280
W=310
H=50
FontColor=#COL2#
FontFace=#F#
StringAlign=Center
AntiAlias=1
ClipString=1
FontSize=#F5#

[WMeterIconF]
Meter=Image
MeasureName=MeasureWeatherIconF
Path="#CURRENTPATH#WeatherIcons Big"
X=0
Y=0



[WMeterTF]
Meter=String
MeasureName=WMeasureTF
X=140
Y=15
W=200
H=80
FontColor=250,250,250,250
StringStyle=NORMAL
StringEffect=SHADOW
FontFace=calibri
StringAlign=Left
FontEffectColor=0,0,0,80
AntiAlias=1
ClipString=1
FontSize=35
Postfix=" °C"

[WMeterON]
Meter=String
MeasureName=WMeasureON
X=340
Y=129
W=255
H=35
FontSize=12
FontColor=250,250,250,250
StringStyle=BOLD
StringEffect=SHADOW
FontFace=calibri
StringAlign=Left
FontEffectColor=0,0,0,80
AntiAlias=1
ClipString=1
Prefix="Ощущаемая температура: "

[WMeterFD]
Meter=String
MeasureName=WMeasureFD
X=340
Y=20r
W=255
H=35
FontSize=12
FontColor=250,250,250,250
StringStyle=BOLD
StringEffect=SHADOW
FontFace=calibri
StringAlign=Left
FontEffectColor=0,0,0,80
AntiAlias=1
ClipString=1
Prefix="Давленение: "


[WMeterOW]
Meter=String
MeasureName=WMeasureOW
X=340
Y=20r
W=255
H=35
FontSize=12
FontColor=250,250,250,250
StringStyle=BOLD
StringEffect=SHADOW
FontFace=calibri
StringAlign=Left
FontEffectColor=0,0,0,80
AntiAlias=1
ClipString=1
Prefix="Влажность: "

[WMeterwind]
Meter=String
MeasureName=WMeasurewind
X=340
Y=190
W=170
H=35
FontSize=12
FontColor=250,250,250,250
StringStyle=BOLD
StringEffect=SHADOW
FontFace=calibri
StringAlign=Left
FontEffectColor=0,0,0,80
AntiAlias=1
ClipString=1
Prefix="Скорость ветра: "

[WMeterIconWet]
Meter=Image
MeasureName=WMeasureWET
Path="#CURRENTPATH#WeatherIcons W"
X=5R
Y=190

[WMeterwind2]
Meter=String
MeasureName=WMeasureWET2
X=5R
Y=190
W=10
H=35
FontSize=12
FontColor=250,250,250,250
StringStyle=BOLD
StringEffect=SHADOW
FontFace=calibri
StringAlign=Left
FontEffectColor=0,0,0,80
AntiAlias=1
 









































